FROM node:20-alpine
WORKDIR /app
COPY package*.json tsconfig.json ./
RUN npm install --strict-ssl=false
COPY src/ ./src/
CMD ["npx", "typeorm-ts-node-commonjs", "migration:run", "-d", "src/data-source.ts"]
